### ISSUE TITLE
Scraper not working for me

### ISSUE THREAD

**Issue by dholt** [tylerhall/sosumi#1]
Hi,  

I get no output from the scraper when I use the simple example.  I've spent a few hours trying to get this to work with no luck.  The best I can figure is that it's dieing around line 49 in class.sosumi.php when it tries to fetch the URL "https://secure.me.com/wo/WebObjects/DockStatus.woa/wa/trampolinehttps://auth.apple.com/authenticate" (the value of $trampoline).  If I go to "https://secure.me.com/wo/WebObjects/DockStatus.woa/wa/trampoline" in my browser when I'm authenticated, I just get a 404 page.  Any hints?  Thanks,

Doug

**Comment by dholt** [comment]
Actually it looks like my real issue is going to this URL: "https://secure.me.com/wo/WebObjects/DeviceMgmt.woa/?lang=en".  I just get a blank page that says "Unauthorized".

**Comment by tylerhall** [comment]
Apple has updated their login system and subsequently broken Sosumi. I haven't dug into their new HTML to fix it yet.

**Comment by ghost** [comment]
So is this code dead then?

**Comment by liviooo** [comment]
I would like to see an update to get it working again :-)

**Comment by dholt** [comment]
Apple changed a value in their authentication cookie that caused the scraper to fail.  I've talked to tylerhall about it and he said this version is working for him again.  I've implemented a working solution in python since I can't do this sort of thing in PHP ;-P. 

http://github.com/dholt/location/tree/master

**Comment by liviooo** [comment]
Bizar .... it should work in php according to http://nat.org/blog/2009/08/playnice-google-apple/ .... and I can confirm !

**Comment by ghost** [comment]
Sadly, can't get that script working either :( Won't get location from iphone - seems a lot of other people are having similar issues.

**Comment by dholt** [comment]
Just modify it to strip the quotation marks from the version value in the authentication cookie, works great!

**Comment by tylerhall** [comment]
Just checking in to say Sosumi is still working as of 9/27/2009.
