### ISSUE TITLE
Investigate report of broken functionality

### ISSUE THREAD

**Issue by tylerhall** [tylerhall/sosumi#10]
"@tylerhall it looks like recent updates to MobileMe broke Sosumi (and Playnice, etc). Says I have no iPhones when I have three. Any ideas?"

http://twitter.com/#!/BeauGiles/status/1394430938447872

**Comment by kita-zz** [comment]
I second that the script is indeed broken after the latest updates to MobileMe.

**Comment by tylerhall** [comment]
Give the latest revision a try.
