### ISSUE TITLE
7am - November 22, 2010

### ISSUE THREAD

**Issue by five337** [tylerhall/sosumi#11]
I think apple broke this with the release of the new iOS.

I did not update any of my devices, but GPS location seemed to stop coming in right after 7am this morning.

**Comment by filid** [comment]
PHP Fatal error:  Uncaught exception 'Exception' with message 'Error parsing json string' in class.sosumi.php:98
Stack trace:
#0 class.sosumi.php(27): Sosumi->updateDevices()
#1 test.php(18): Sosumi->__construct('APPLEID', 'PASSWORD)
#2 {main}
  thrown in class.sosumi.php on line 98

Stopped working around 2010/11/22 15:45 CET

**Comment by filid** [comment]
After the latest fix it does loop forever with 330 for me. The website and the iPhone app is working and does locate me perfectly.

**Comment by jeremysanchez** [comment]
Same for me.  The latest fix just continues to loop until the server times out and displays a 500 error.

**Comment by filid** [comment]
fix from abyler works, if you use the class.sosumi.scraper.php

**Comment by kita-zz** [comment]
After Apple changed MobileMe to include free access to Find My iPhone, this script broke. I cannot get it to work either using class.sosumi.php or class.sosumu.scraper.php. Originally using it from Playnice, but running it directly doesn't work either. Hopefully a fix will be found soon.

**Comment by jonchui** [comment]
I can't get it to work as well.

When i roll back to class.sosumi.scraper.php it doesn't work either.

**Comment by five337** [comment]
I have the class.sosumi working again by changing the client version from 1.0 to 1.1. The iPhone app requires 1.1 now.

You also have to add @me.com to the end of your user name.

**Comment by tylerhall** [comment]
five337, could you send me a copy of class.sosumi.php that is working for you? I'm unable to work around the new errors and would love to update the project with a working script. tylerhall AT gmail DOT com

**Comment by five337** [comment]
Well I spoke too soon. I was using an older version of the script and updated the 1.1 and build 99 values myself. The current version of the script you have works the same.

I use it as part of my home automation. It polls mobileme every 10 mins to see where we are. I would say it works 2 out of 5 times for the main person on the mobileme account and no matter what I do; I can't get it to work on one of the additional family accounts. 

It used to be rock solid. 

I've also experienced some oddities with the mobileme website since they updated. On the "additional" accounts it will tell me that the findme option is not enabled on the phone. Then after a while it will start to work again.

Adding @me.com to the end of the user name seems to be a must now.

When it fails - it fails very quickly; just a quick as when you have bad credentials. 

I have access to a few PAID mobile me accounts - I'll try to figure out a pattern. It just seems so random right now.

**Comment by ghost** [comment]
This is related to the new partitioning, hence the sometimes works, sometimes doesn't.

The initial response to the .../initClient has a header named 'X-Apple-MME-Host'.  Replacing 'fmipmobile.me.com' with the value of that header in the URL for all subsequent request should work no problem.  'fmipmobile.me.com' hits a random partition and if it happens to be the partition your account is on, things will work just fine, if it happens to be a different one, you will get the 330 loop.

**Comment by tylerhall** [comment]
Brilliant. Thanks, Mike.
