### ISSUE TITLE
only one device visible

### ISSUE THREAD

**Issue by eldrik** [tylerhall/sosumi#12]
Hi,

I thought sosumi would display all of my iOS devices (iPad, iPhone).

Can someone assist me expanding the needed functions or is there a general problem with more then one device?

Regards
Eldrik

**Comment by tylerhall** [comment]
After instantiating your Sosumi object, the $devices property will contain an array of all your devices.

**Comment by ghost** [comment]
Should be supported out of the box, the various functions take an optional device number argument which defaults to 0.
