### ISSUE TITLE
No luck with 'free' Accounts

### ISSUE THREAD

**Issue by BeauGiles** [tylerhall/sosumi#13]
Just updated my installation of sosumi (for playnice) and am now trying my new 'free' Find my iPhone Apple ID account. Unfortunately, it doesn't seem to want to accept my account, no matter what I try.

I am using the full address (beau at beaugil dawt es) and have made sure there's no special characters in my password, etc.
I can get my partner's MobileMe account working by using his full address (username at me dawt com) and password (same as mine for testing).

Any ideas for fixing?

**Comment by BeauGiles** [comment]
UPDATE: I'm able to get it working with the latest version of sosumi and this version of playnice.php https://github.com/ablyler/playnice/raw/fede32af2bd231ed3275aeefa059a24647d22975/playnice.php - though there's still some errors re log files and such,

**Comment by tylerhall** [comment]
Give the latest revision a try.
