### ISSUE TITLE
Looping though there is a valid location response.....(see debug code enclosed)

### ISSUE THREAD

**Issue by ravenmcsmith** [tylerhall/sosumi#14]
Hello,

I am running into a problem with the new script.

It sometimes loops for ever, though there is a real location in the answer:

```
"longitude":xxxxxxxxxxxxxxx,"latitude":xxxxxxxxxxxxxxx,
```

but it continues the loop 

```
 ...
 Parsing 1 devices...
 Waiting for location...
 updateDevices...
 …
```

(See enclosed debug code below.)

I think this is due to the loops condition

```
while($this->devices[$device_num]->locationFinished != 1)
```

which will loop because the answer is

```
"locationFinished":false
```

though there is a real location mentioned in the answer (which seems to come from wifi positioning).

Any ideas how to solve this problem?
Has this something to do with the positionType Wifi?
Has this something to do with impossible GPS positioning due to location inside a building and using WiFi positioning as alternative?

Many thanks & bye
Raven

Ps: 

a) Would be very neat to also be able to use your class to get attributes like:
- "positionType":"Wifi" (What's the other? GPS?)
- "preferredLanguage"
- "tzCurrentName"
- "validRegion":true (What would be an invalid region? ;-))

b) In the new version you are using  the "deviceUDID" zero'ed. Shouldn't we try to use our own id? How do we get our id? Any ideas?

--cut here debug code--

Getting partition...
URL: https://fmipmobile.me.com/fmipservice/device/MobileMeUserID/initClient
POST DATA: {"clientContext":{"appName":"FindMyiPhone","appVersion":"1.1","buildVersion":"99","deviceUDID":"0000000000000000000000000000000000000000","inactiveTime”:xxxxxxxxxxx,"osVersion":"4.2.1","personID":0,"productType":"iPad1,1"}}
updateDevices...
URL: https://p01-fmipmobile.me.com/fmipservice/device/MobileMeUserID/initClient
POST DATA: {"clientContext":{"appName":"FindMyiPhone","appVersion":"1.1","buildVersion":"99","deviceUDID":"0000000000000000000000000000000000000000","inactiveTime”:xxxxxxxxxxx,"osVersion":"4.2.1","personID":0,"productType":"iPad1,1"}}
updateDevices Returned: {"statusCode":"200","content":[{"isLocating":true,"b":yyyyyy,"remoteWipe":null,"location":{"timeStamp":xxxxxxxx,"positionType":"Wifi","horizontalAccuracy":100.0,"locationFinished":false,"longitude":xxxxxx,"latitude":xxxxxx,"isOld":false},"a":"Charging","deviceModel":"FourthGen","deviceStatus":"203","remoteLock":null,"msg":null,"locationEnabled":true,"id":" xxxxxxxxxxxxxxx","thisDevice":false,"deviceDisplayName":"iPhone 4","name":"iPhone","deviceClass":"iPhone","features":{"MSG":true,"CWP":false,"REM":false,"LCK":true,"SND":true,"KEY":false,"LOC":true,"WIP":true}}],"userPreferences":{"lastUpdatedTime":xxxxxxxxxxxxxxx,"webPrefs":{"id":"web_prefs","selectedDeviceId":"Xxxxxxxxxxxxxxx"},"builder":null},"serverContext":{"prefsUpdateTime":xxxxxxxxxxxxxxx,"maxDeviceLoadTime":60000,"authToken":"Xxxxxxxxxxxxxxx","classicUser":false,"sessionLifespan":900000,"deviceLoadStatus":"200","preferredLanguage":"xx-xx","lastSessionExtensionTime":null,"clientId":"Xxxxxxxxxxxxxxx","timezone":{"tzCurrentName":"Xxxxxx","previousTransition":xxxxxx,"previousOffset":xxxxxx,"currentOffset":xxxxxx,"tzName":"Xxxxxx"},"callbackIntervalInMS":10000,"validRegion":true,"maxLocatingTime":90000,"hasDevices":true,"prsId":xxxxxxxxxxxxxxx}}
Parsing 1 devices...
Waiting for location...
updateDevices...
URL: https://p01-fmipmobile.me.com/fmipservice/device/MobileMeUserID/initClient
POST DATA: {"clientContext":{"appName":"FindMyiPhone","appVersion":"1.1","buildVersion":"99","deviceUDID":"0000000000000000000000000000000000000000","inactiveTime”:xxxxxxxxxxx,"osVersion":"4.2.1","personID":0,"productType":"iPad1,1"}}
updateDevices Returned: {"statusCode":"200","content":[{"isLocating":true,"b":yyyyyy,"remoteWipe":null,"location":{"timeStamp":xxxxxx,"positionType":"Wifi","horizontalAccuracy":100.0,"locationFinished":false,"longitude":xxxxxxxxxxxxxxx,"latitude":xxxxxxxxxxxxxxx,"isOld":false},"a":"Charging","deviceModel":"FourthGen","deviceStatus":"203","remoteLock":null,"msg":null,"locationEnabled":true,"id":"Xxxxxxxxxxxxxxx","thisDevice":false,"deviceDisplayName":"iPhone 4","name":"iPhone","deviceClass":"iPhone","features":{"MSG":true,"CWP":false,"REM":false,"LCK":true,"SND":true,"KEY":false,"LOC":true,"WIP":true}}],"userPreferences":{"lastUpdatedTime":xxxxxxxxxxxxxxx,"webPrefs":{"id":"web_prefs","selectedDeviceId":"Xxxxxxxxxxxxxxx"},"builder":null},"serverContext":{"prefsUpdateTime":xxxxxxxxxxxxxxx,"maxDeviceLoadTime":60000,"authToken":"Xxxxxxxxxxxxxxx","classicUser":false,"sessionLifespan":900000,"deviceLoadStatus":"200","preferredLanguage":"xx-xx","lastSessionExtensionTime":null,"clientId":"Xxxxxxxxxxxxxxx","timezone":{"tzCurrentName":"Xxxxxx","previousTransition":xxxxxx,"previousOffset":xxxxxx,"currentOffset":xxxxxx,"tzName":"Xxxxxx"},"callbackIntervalInMS":10000,"validRegion":true,"maxLocatingTime":90000,"hasDevices":true,"prsId":xxxxxxxxxxxxxxx}}
Parsing 1 devices...
Waiting for location...
updateDevices...
URL: https://p01-fmipmobile.me.com/fmipservice/device/MobileMeUserID/initClient
POST DATA: {"clientContext":{"appName":"FindMyiPhone","appVersion":"1.1","buildVersion":"99","deviceUDID":"0000000000000000000000000000000000000000","inactiveTime”:xxxxxxxxxxx,"osVersion":"4.2.1","personID":0,"productType":"iPad1,1"}}
updateDevices Returned: {"statusCode":"200","content":[{"isLocating":true,"b":yyyyyy,"remoteWipe":null,"location":{"timeStamp":xxxxxx,"positionType":"Wifi","horizontalAccuracy":100.0,"locationFinished":false,"longitude":xxxxxxxxxxxxxxx,"latitude":xxxxxxxxxxxxxxx,"isOld":false},"a":"Charging","deviceModel":"FourthGen","deviceStatus":"203","remoteLock":null,"msg":null,"locationEnabled":true,"id":"Xxxxxxxxxxxxxxx","thisDevice":false,"deviceDisplayName":"iPhone 4","name":"iPhone","deviceClass":"iPhone","features":{"MSG":true,"CWP":false,"REM":false,"LCK":true,"SND":true,"KEY":false,"LOC":true,"WIP":true}}],"userPreferences":{"lastUpdatedTime":xxxxxxxxxxxxxxx,"webPrefs":{"id":"web_prefs","selectedDeviceId":"Xxxxxxxxxxxxxxx"},"builder":null},"serverContext":{"prefsUpdateTime":xxxxxxxxxxxxxxx,"maxDeviceLoadTime":60000,"authToken":"Xxxxxxxxxx","classicUser":false,"sessionLifespan":900000,"deviceLoadStatus":"200","preferredLanguage":"xx-xx","lastSessionExtensionTime":null,"clientId":"Xxxxxxxxxx","timezone":{"tzCurrentName":"Xxxxxx","previousTransition":xxxxxx,"previousOffset":xxxxxx,"currentOffset":xxxxxx,"tzName":"Xxxxxx"},"callbackIntervalInMS":10000,"validRegion":true,"maxLocatingTime":90000,"hasDevices":true,"prsId":xxxxxxxxxxxxxxx}}
Parsing 1 devices...
Waiting for location...
updateDevices...
URL: https://p01-fmipmobile.me.com/fmipservice/device/MobileMeUserID/initClient

**Comment by ghost** [comment]
The locate method takes an optional max time to wait for a fix, it defaults to 300 seconds.  You can specify a shorter alternate value.

**Comment by ravenmcsmith** [comment]
That is not really the point. Setting the max time to wait for example to 20, will produce this exception:
     Unable to find location within '20' seconds

My issue report questions the _reason_ for the loop I am experiencing.
The webservice answer has a valid longitude and latitude, but doesn't set the flag locationFinished to true. Why does that happen?
Any ideas on that?
