### ISSUE TITLE
Lot of error messages

### ISSUE THREAD

**Issue by Scubydoo** [tylerhall/sosumi#15]
Hello, I'm trying to include the script on my website. By using the class.sosumi.php I got the following error message:
Warning: curl_setopt() [function.curl-setopt]: CURLOPT_FOLLOWLOCATION cannot be activated when in safe_mode or an open_basedir is set in .../class.sosumi.php on line 163

Sometimes, the google map will be displayed. I changed the line 163 to:
curl_setopt($ch, CURLOPT_URL, "http://.../position");

But now, the following error comes up. 

Fatal error: Uncaught exception 'Exception' with message 'Error parsing json string''' in /.../class.sosumi.php:109 Stack trace: #0 /.../class.sosumi.php(29): Sosumi->updateDevices() #1 /.../index.php(11): Sosumi->__construct(Username, Password) #2 {main} thrown in /.../class.sosumi.php on line 109

I can't change the safe_mode or open_basedir parameter from my webhoster!

What can I do to avoid this message!

Thanks in advance

Best regards

Scubydoo

**Comment by tylerhall** [comment]
I'm afraid you're out of luck for the moment. The only way I know around the problem (with safe_mode enabled) is to parse each curl response for a redirect header and then manually initiate another request to the new url.

The json error is likely a result of curl not being able to follow the redirect and returning a bunch of garbage data instead.

**Comment by Scubydoo** [comment]
I looked into the phpinfo() output:
safe_mode Off 

but the parameter open_basedir = /home/www/.../ is set. I thinks that's the main problem. And I don't know if I can avoid this?!?

'The only way I know around the problem (with safe_mode enabled) is to parse each curl response for a redirect header and then manually initiate another request to the new url.'

I'm not the php expert and therefore i'm not able to include this solution :-(

**Comment by Batchman** [comment]
Try

curl_setopt($ch, CURLOPT_FOLLOWLOCATION, false);

and

curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

Worked for me.

**Comment by xheliosx** [comment]
I'm getting an internal server error. What's the most likely cause? I have secure hosting.

"The server encountered an internal error or misconfiguration and was unable to complete your request."

**Comment by tylerhall** [comment]
@xheliosx Sorry, that's not enough information to go on.

**Comment by xheliosx** [comment]
Yeah, sorry...I'm new to this. Problem resolved by removing inactive devices from me.com account. Anyways, this is amazing! Thanks so much for keeping this updated.
