### ISSUE TITLE
Fatal error:  Uncaught exception

### ISSUE THREAD

**Issue by bobbymanson** [tylerhall/sosumi#16]
Since Apple's FMIP change in Nov and the script's updates, I cannot get a reliable execution.  Here is the output from the script.

Fatal error: Uncaught exception 'Exception' with message 'Error parsing json string' in /Utility/fmip/class.sosumi.php:109
Stack trace:
#0 /Utility/fmip/class.sosumi.php(29): Sosumi->updateDevices()
#1 /Utility/fmip/bobby.php(4): Sosumi->__construct('bobbymanson', '********')
#2 {main}

  thrown in /Utility/fmip/class.sosumi.php on line 109

This is the calling script's code:

<?
date_default_timezone_set('America/Chicago');
include '/Utility/fmip/class.sosumi.php';
$ssm = new Sosumi('bobbymanson', '*******');
print_r($ssm->locate(1));
?>

Any help would be appreciated.  Thanks

**Comment by tylerhall** [comment]
It's working for me as of five minutes ago. Two things to check:

1) Make sure you're using the most recent version of the code from GitHub (sorry if this seems obvious).

2) Also, Apple's recent changes require that you use your full Apple ID in your credentials. i.e., you have to now use "username@me.com" rather than just "username".

**Comment by bobbymanson** [comment]
Yeah, I have the latest version of the script.  It was working at least some of the time on my account, but not at all on the sub accounts.  Now it's not working at all.  Would you tell me if there is anything wrong with my calling script?  Thanks for your help.

<?
date_default_timezone_set('America/Chicago');
include '/Utility/fmip/class.sosumi.php';
$ssm = new Sosumi('bobbymanson@me.com', '**********');
print_r($ssm->locate(1));
?>

**Comment by bobbymanson** [comment]
Never mind.  I think that I found it.  Looks like the last line somehow merged the last two lines in my calling script.  VI never showed it.  Thanks.  Awesome script and the Mac Desktop version rocks!!!

**Comment by tylerhall** [comment]
Glad it's working!
