### ISSUE TITLE
Sosumi no longer woeking after todays Maintanance Update?

### ISSUE THREAD

**Issue by xheliosx** [tylerhall/sosumi#17]
Appears the the me.com password isnt being sent after the maintenance update today. I'm getting 'Warning: fgets(): supplied argument is not a valid stream resource in ...'

Anyone else see this?

**Comment by tylerhall** [comment]
I just confirmed that Sosumi is still working after today's update.

Also, I'm a little confused. Sosumi doesn't used fgets(). Could the error you're seeing be coming from somewhere else?

**Comment by xheliosx** [comment]
It was an issue with my account, everything works great. This project is awesome.
