### ISSUE TITLE
Not working on 3/29/2011?

### ISSUE THREAD

**Issue by MitchellVincent** [tylerhall/sosumi#18]
PHP Fatal error:  Uncaught exception 'Exception' with message 'Error parsing json string' in class.sosumi.php:112\nStack trace:\n#0 class.sosumi.php(29): Sosumi->updateDevices()\n#1 example.php(9): Sosumi->__construct('MyUsername', 'MyPassword', true)\n#2 {main}\n  thrown in class.sosumi.php on line 112

I print the "$response" variable from the getPartition() function and I see this : 

HTTP Status 401 -
type Status report
message
description This request requires HTTP authentication ().
Apache Tomcat/6.0.29

**Comment by tylerhall** [comment]
I just tested the latest version and everything worked correctly. I was able to retrieve my location and send a push notification message to my device. It's possible there was a hiccup in the service or that your credentials are wrong. Make sure you include the @me.com part of your username.

**Comment by MitchellVincent** [comment]
Thanks Tyler. Sort of crazy - I've tried 4 different servers with 4 different sets of credentials (all verified) and get the same error every time. I'll keep trying but thanks for the reply!

**Comment by MitchellVincent** [comment]
Geeze.. Sorry about this. Found the problem. We were copy/pasting all the credentials from another source and there was an extra character in all the passwords. It works great! ;-)

**Comment by tylerhall** [comment]
No worries - glad it's working.
