### ISSUE TITLE
This should work on free accounts right?

### ISSUE THREAD

**Issue by jgshier** [tylerhall/sosumi#20]
Getting partition... URL: https://fmipmobile.me.com/fmipservice/device/*****@gmail.com/initClient POST DATA: {"clientContext":{"appName":"FindMyiPhone","appVersion":"1.1","buildVersion":"99","deviceUDID":"0000000000000000000000000000000000000000","inactiveTime":2147483647,"osVersion":"4.2.1","personID":0,"productType":"iPad1,1"}} updateDevices... URL: https:///fmipservice/device/*****@gmail.com/initClient POST DATA: {"clientContext":{"appName":"FindMyiPhone","appVersion":"1.1","buildVersion":"99","deviceUDID":"0000000000000000000000000000000000000000","inactiveTime":2147483647,"osVersion":"4.2.1","personID":0,"productType":"iPad1,1"}} updateDevices Returned:

Fatal error: Uncaught exception 'Exception' with message 'Error parsing json string' in C:\inetpub\SecureSite\iphone\class.sosumi.php:110 Stack trace: #0 C:\inetpub\SecureSite\iphone\class.sosumi.php(29): Sosumi->updateDevices() #1 C:\inetpub\SecureSite\iphone\example.php(9): Sosumi->__construct('emailaddress', '*****') #2 {main} thrown in C:\inetpub\SecureSite\iphone\class.sosumi.php on line 110

I confirmed my password does not have any crazy characters and not extra characters on the code like I see others have had.

**Comment by jgshier** [comment]
Issue fixed by changing the curl SSL setting. But I am still getting an error at the top of the page.

HTTP/1.1 330 Unknown

Server: Apache-Coyote/1.1

X-Apple-MMe-Host: p02-fmipmobile.me.com

X-Apple-MMe-Scope: 210366097

X-Transaction-Id: 955f21df-ef9b-4369-9313-eab674987853

X-Responding-Server: nk11p04me-fmipapp002_004

X-Responding-Partition: p04

Content-Length: 0

Date: Thu, 28 Apr 2011 04:51:37 GMT

Connection: keep-alive

Set-Cookie: NSC_q04-gnjqbqq=ffffffff1296085045525d5f4f58455e445a4a422974;path=/;secure;httponly

**Comment by tylerhall** [comment]
No issues here. Just tested and everything worked fine.

Which curl SSL setting did you have to change?

**Comment by ersan** [comment]
I'm having the same problem problem at the moment

**Comment by tylerhall** [comment]
It's currently broken due to a combination of changes made on Apple's side and Lion. It's on my list of things to fix, but since Sosumi is free, I'm not sure when I'll have time to get to them. But I'm a user, too, so I want to see it working again as well :-)

**Comment by ersan** [comment]
I'll take a crack at fixing it in a bit, thanks for letting me know I couldn't find any tickets about it so I assumed I was doing something wrong.
