### ISSUE TITLE
Error parsing json string

### ISSUE THREAD

**Issue by and77** [tylerhall/sosumi#21]
Hi,
I am trying to run this on the free web space of square7.ch .

Yesterday it worked after I entered
https://fmipmobile.me.com/fmipservice/device/ in line 143 in class.sosumi.php for https:// 
and
set curl_setopt($ch, CURLOPT_FOLLOWLOCATION, false); to false in line 163 of class.sosumi.php.

However, today it is not working. I only get this:

Fatal error: Uncaught exception 'Exception' with message 'Error parsing json string' in /users/username/www/aa/class.sosumi.php:109 Stack trace: #0 /users/username/www/aa/class.sosumi.php(29): Sosumi->updateDevices() #1 /users/username/www/aa/example.php(9): Sosumi->__construct('correctmailaddress', 'password') #2 {main} thrown in /users/username/www/aa/class.sosumi.php on line 109
1. What bugs me is, that in the error message the password is in clear text!!
2. Obviously, what bugs me even more: it is not working. ;-)

Any ideas how to fix these issues or by what they are caused?
Thanks!

**Comment by tylerhall** [comment]
1. PHP knows your password - therefore, if it errors, there's a chance it could be listed in the backtrace. The only way around this is to
   - Turn off display_errors if you're running Sosumi via the browser and
   - Ensure your PHP error logs are kept private on your server.
2. I just tested Sosumi and it worked fine. It's possible there was a slight hiccup on Apple's end or maybe a network error - but the code is currently working. That said, you should not need to modify _anything_ in class.sosumi.php - especially nothing on line 143. All you need to do is
   
   $ssm = new Sosumi('username@me.com', 'password');
   $ssm->locate();
   print_r($ssm);

I would try again with a clean installation of Sosumi. Most problems other users have reported have boiled down to safe mode or other restrictions put in place by their hosting providers.

Cheers.
Tyler
