### ISSUE TITLE
503 Service Unavailable?

### ISSUE THREAD

**Issue by digidanny** [tylerhall/sosumi#23]
Is this still supported?  The first POST request to 

"/fmipservice/device/{$this->username}/initClient"

is getting a 503 service unavailable error.

**Comment by bschollnick** [comment]
I am seeing the same issue, with the updated versions of Autolat & RecordMyLatitude's python port of sosumi.

And in Sosumi as well, just slightly different...

dhcp105-48:PHP Benjamin$ php example.php
PHP Notice:  Undefined offset: 1 in /Users/Benjamin/Downloads/tylerhall-sosumi-d312af5/PHP/class.sosumi.php on line 42
PHP Fatal error:  Uncaught exception 'Exception' with message 'Error parsing json string' in /Users/Benjamin/Downloads/tylerhall-sosumi-d312af5/PHP/class.sosumi.php:113
Stack trace:
#0 /Users/Benjamin/Downloads/tylerhall-sosumi-d312af5/PHP/class.sosumi.php(33): Sosumi->updateDevices()

**Comment by goddva** [comment]
There is a new Find My iPhone app out, so you would need to correct the version number in the class.

Replace all (5 places)
  "appVersion":"1.2",
with
  "appVersion":"1.2.1",

and then
  $headers[] = 'User-agent: Find iPhone/1.2 MeKit (iPad: iPhone OS/4.2.1)';
with
  $headers[] = 'User-agent: Find iPhone/1.2.1 MeKit (iPad: iPhone OS/4.2.1)';

**Comment by albeebe** [comment]
Thank you goddva that worked great! Finally after 2 weeks i got this working again with your little fix.

**Comment by tylerhall** [comment]
I've updated the source to reflect @goddva's changes. Thanks!
