### ISSUE TITLE
Stopped working for me today

### ISSUE THREAD

**Issue by naek** [tylerhall/sosumi#25]
Congrats on you work, it has been working flawlessly for weeks. Unfortunately, it stopped working today.

Did Apple make any changes to prevent sosumi from working? The iCloud website and FindMyIphone app still works however.

I get error:
Fatal error: Uncaught exception 'Exception' with message 'Unable to find location within '25' seconds ' in class.sosumi.php:55

The php page timesout if I Changing $max_wait to default value of 300.

**Comment by tylerhall** [comment]
I just ran a quick test and it worked for me. It was likely just a temporary hiccup.
