### ISSUE TITLE
locate() seems to hang indefinately

### ISSUE THREAD

**Issue by FattusMannus** [tylerhall/sosumi#27]
Using the most basic example of 

```
set_time_limit(0);
require 'class.sosumi.php';


// Enter your MobileMe username and password
$ssm = new Sosumi('XXX', 'XXX');
$loc = $ssm->locate();

print_r($loc);
```

Seems to hang indefinately - what am I doing wrong?

**Comment by FattusMannus** [comment]
Correction: I eventually get Fatal error: Uncaught exception 'Exception' with message 'Unable to find location within '300' seconds

**Comment by tylerhall** [comment]
Unfortunately, that means Sosumi is working - Apple just isn't able to pull your device's location in a reasonable amount of time. Try logging into Apple's real Find My iPhone app or website to see if they're able to determine your location. Then try Sosumi again.

**Comment by FattusMannus** [comment]
I have tried this - Find my iPhone works and so does icloud.com
I have tried the code from 3 different servers to ensure it wasnt some hosting limitation too.

**Comment by FattusMannus** [comment]
I have tried on a different account with just one device in the account and it works fine :)

On my account it seems to be looping on updateDevices(), is there anything else I can do to help in debugging the issue?

**Comment by FattusMannus** [comment]
Ok, ive worked it out
Apples Service is hanging trying to find one of my devices, specifying the DeviceID worked for me

Thanks
