### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by maciekish** [tylerhall/sosumi#29]
Hi,
I tried on a fully patched Ubuntu server and my box over at nosupportlinuxhosting and the example.php page just sits around loading. I have set my Google Maps API key and login for Apple. Both servers have PHP 5.3.x, curl with SSL and JSON.

What could be wrong, and how do i get some debug output please?

Thanks

**Comment by maciekish** [comment]
After 5mins without refreshing i got:

Fatal error: Uncaught exception 'Exception' with message 'Unable to find location within '300' seconds ' in /home/a409/public_api/sosumi/class.sosumi.php:55 Stack trace: #0 /home/a409/public_api/sosumi/example.php(10): Sosumi->locate() #1 {main} thrown in /home/a409/public_api/sosumi/class.sosumi.php on line 55

Signing in to icloud.com works for finding devices. Does it matter if i have several devices?

**Comment by tylerhall** [comment]
It's possible one of the devices on your account is offline, causing the script to timeout. Try running this and see if you get any better results...

$ssm = new Sosumi('username', 'password');
$ssm->locate();
print_r($ssm);

**Comment by maciekish** [comment]
It worked now, thanks.

How do i make sure i get the location of the device i want? As far as i can see i can only request the location by the index, which could possibly change? Any way to request by UDID or name?

**Comment by tylerhall** [comment]
You can loop through the $devices array to find the specific device you're looking for.
