### ISSUE TITLE
Not working with PHP 5.2

### ISSUE THREAD

**Issue by 040medien** [tylerhall/sosumi#3]
I've discovered an issue when running this on the latest stable Debian or Ubuntu, which both have PHP 5.2 and a somewhat older cURL module installed. Other people are seeing this as well: http://nat.org/blog/2009/08/playnice-google-apple/comment-page-1/#comment-4887
Can you please narrow this down?

**Comment by liviooo** [comment]
I also have problems when trying this on my ISS6+PHP v5.2.6.

Fetching iPhone location...
Notice: Undefined index: secure.me.com in D:\web\mysite.com\findmyiphone\class.sosumi.php on line 141

Notice: Undefined index: secure.me.com in D:\web\ mysite.com\findmyiphone\class.sosumi.php on line 148

Notice: Undefined index: secure.me.com in D:\web\ mysite.com\findmyiphone\class.sosumi.php on line 88

What can I do about it ?
