### ISSUE TITLE
Correct position with second try only

### ISSUE THREAD

**Issue by bottervogel** [tylerhall/sosumi#31]
I have a problem with sosumi: it shows the correct position only on the second try after waiting some seconds after the first try. Is this behavior normal? What do you suggest? Add a sleep()-command into the script and another sosumi function call?

The first call always shows an old location.

**Comment by albeebe** [comment]
This is basically how Apple handles things.  When you make a request, Apple will return a location (if it has one already) then it will ping your phone to send a new location.  Thats why the second request always has a new location

**Comment by matbor** [comment]
Is there a way then, to have it supply the previous location and then make
it wait until the new location has been received?

**Comment by albeebe** [comment]
In your code just do two $ssm->locate() calls in a row
