### ISSUE TITLE
Example.php doesn't seem to work anymore

### ISSUE THREAD

**Issue by johanndiedrick** [tylerhall/sosumi#33]
Hello-

I've been trying to spend some time getting example.php to run and it doesn't seem to be doing anything. The first major hurdle was realizing that Google Maps API has moved on to V3, so the script you want to call is:

```
<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=API_KEY&sensor=SET_TO_TRUE_OR_FALSE">
</script>
```

Referenced here: https://developers.google.com/maps/documentation/javascript/tutorial#HelloWorld

From there, I am only able to get the page to load by uncommenting most of what's in the top PHP code:

 <? PHP
     require 'class.sosumi.php';

```
 // You'll need to enter your own Google Maps API key
 // Get one from here: http://code.google.com/apis/maps/signup.html
 $google_maps_key = 'API_KEY';

 /*
 // Enter your MobileMe username and password
 $ssm = new Sosumi('your_username', 'your_password');
 $loc = $ssm->locate();

 if(isset($_POST['btnSend']))
 {   
     $alarm = isset($_POST['alarm']); 
     $ssm->sendMessage($_POST['msg'], $alarm);
     header('Location: ' . $_SERVER['PHP_SELF']);
 }

  */
```

 ?>

If I start my comment after where I enter my MobileMe username and password, the page stops loading. I'm wondering if there is a deeper bug in class.sosumi.php, but I'm not sure where to start looking. Any help would be appreciated!

**Comment by scheibome** [comment]
Have you tried your e-mail address instead of username? I think this will fix your problem.

**Comment by johanndiedrick** [comment]
Thank you, that solved that problem. I can now send notifications to my computer, but they don't seem to show up on my iPhone (they're under the same account).

Also, the map doesn't seem to show up as well on the page. I'm going through and looking to update some of the js, because it seems like some of the function calls are outdated. For example, 

var map = new GMap2(document.getElementById("map_canvas"));

seems to now need to be

var map = google.maps.Map(document.getElementById("map-canvas"), mapOptions);

**Comment by tylerhall** [comment]
Map example is no longer being maintained. Closing this issue.
