### ISSUE TITLE
Entering/leaving area

### ISSUE THREAD

**Issue by kristianolofsson** [tylerhall/sosumi#34]
Id really love if the entering or leaving a certain area Could be managed.

I see  really good opportunity for such a script.

I'd like the script to check that if my location match within the range of eg my home send a http request to a spec. Url. If it fails, meaning I left the area, send a http request to a different URL.

In this way I can set up the script to run on a recurring basis and if I'm within range send eg a trigger to my home automation system to tell I'm reaching home. Upon I'm not home, do the same and tell my home automation to shut of all lights.

Thanks!

**Comment by matbor** [comment]
Have a look at owntracks.org and mqttwarn

**Comment by kristianolofsson** [comment]
Thanks!

Ill check But I rather prefer not to have an app I believe it will drain my battery.

A server based solution could check the same info in iCloud. Right?

Kristian Olofsson
0736-336291

**Comment by albeebe** [comment]
Kristian,

Every time you use this script to get your location, apple sends a command to your phone to turn on the gps, get your location, then send it back to apple. Each time it does this, it uses your battery. If you were to do this every 10 minutes then your battery would drain so fast.

 I expiremented with this and found that If I wanted to constantly get my location without draining my battery to fast, I could only get my location every 20 minutes. 

You should really investigate ibeacons as they can let you do what you want without the battery drain. 
—

**Comment by kristianolofsson** [comment]
Great! 
ibeacons seems like the thing I'm looking foor. 

I have been looking for multiple options to check if I'm home.
- iPhone connected to my wifi network. Can't get this to work since the iPhone don't seems to connect in sleeping mode.
- iPhone connected via Bluetooth to my iOS server. The problem here is that I don't really want to connect. Just check that it can connect.

So  ibeacons seems like the solution. Only problem here is that it's a very new tech. And can't really find so many existing apps that triggers things like a http request upon entering/leaving my home.

Thanks!

Kristian Olofsson
0736-336291

**Comment by matbor** [comment]
owntracks will drain the battery, but you can play around with settings to minimise that, the advantage is that you can setup a lot of custom functions using openHAB and mqttwarn. 

iBeacon is on the roadmap (well sort of... very distant future!) for owntracks, might end up being a separate app in the end.

here is another option for checking if you are home using just your ip address and python, haven't personally used it...  https://gist.github.com/d3mon187/9744846

**Comment by tylerhall** [comment]
Closing this issue as this functionality would be better off in another script that uses Sosumi, rather than inside Sosumi itself. Feel free to write that script and submit it in a pull request if you'd like it to be in the official repo.
