### ISSUE TITLE
deviceStatus 203

### ISSUE THREAD

**Issue by hotestimator** [tylerhall/sosumi#35]
It seems `deviceStatuses` stays at 203 unless they are "tickled" at  least once by visiting me.com and doing a find. Then any live devices will go to 200. Eventually the live devices revert back to 203 again.

**Comment by tylerhall** [comment]
Hm. I'm seeing that behavior now, too. I'm curious if the latest iOS app update includes a new API call to tickle the devices that we're not aware of. I'll investigate.

**Comment by tylerhall** [comment]
Did some digging. Looks like we were missing a called to /refreshClient that was added to the iOS app sometime in the past. I've added it to Sosumi. Let me know if this helps the situation any.

**Comment by dennisheinzen** [comment]
You changed device_number to device_id 
Is it just a renaming of the variable or does the script now need a device id?
When yes where do i find it?
With the recent class.sosumi.php my script  does not work anymore...

https://gist.github.com/dennisheinzen/f1eca2b01ecb65e4d1e1

**Comment by tylerhall** [comment]
print_r($ssm->devices);

The devices are now indexed by their GUID as returned by Apple. This lets you reliably query a specific device in case the ordering Apple returns them in changes.

The device's id is its index in the devices array, and also in the device->id property.

**Comment by hotestimator** [comment]
Seems to have done the trick. 

```
$ssm = new Sosumi('xxx@xxx.com', 'xxxxxxxxx');

// refresh the clients.
$ssm->refreshClient();

// ... $ssm now has updated data
```

P.S. Thanks for the class!

**Comment by tylerhall** [comment]
Great!
