### ISSUE TITLE
Multiple iphones on same mobileme account how to get info

### ISSUE THREAD

**Issue by ghost** [tylerhall/sosumi#6]
How do I pass the deviceid to locate when trying to select a particular iphone from a multiple iphones mobileme account?

**Comment by tylerhall** [comment]
Unfortunately I don't have two iPhones on my account to test with, but it should work by doing something like this...

```
$ssm = new Sosumi('username', 'password');
$location = $ssm->locate($ssm->devices[0]); // Would get the location of the first phone
$location2 = $ssm->locate($ssm->devices[1]); // Would get the location of the second phone, etc
```

**Comment by ddn** [comment]
Instead of an arbitrary device number, wouldn't it be better to use the GUID as the key? Otherwise we have to trust that the devicenum order is never going to change.

Am I wrong?

**Comment by tylerhall** [comment]
You're right - that would be better. I'll look into making that change (unless someone wants to submit a patch, first).
