### ISSUE TITLE
Multiple Devices

### ISSUE THREAD

**Issue by BeauGiles** [tylerhall/sosumi#8]
I'd like to get this working. Currrently in my playnice.php file, I've tried using

```
// Locate the device
$iphoneLocation = $mobileMe->locate($mobileMe->devices[0]);
```

however this fails. If I just use locate(); it works, but of course I can't set the device.
The problem with using the above code is that I get this error:

Warning: Illegal offset type in /home/beaugile/public_html/playnice/lib/sosumi/class.sosumi.php on line 73

And I'm not quite sure how to fix it?

Line 73 and it's surrounding lines:
       public function locate($device_number = 0)
        {
            return $this->devices[$device_number]->location;

```
    }
```

**Comment by tylerhall** [comment]
Call locate() with just a simple integer value representing the device you want. For example, if you have three devices on your account, you could get their locations via:

```
$phone1 = $mobileMe->locate(0);
$phone2 = $mobileMe->locate(1);
$phone3 = $mobileMe->locate(2);
```

Does that help?

**Comment by BeauGiles** [comment]
Works just fine - cheers Tyler.
