### ISSUE TITLE
Can't get this to work

### ISSUE THREAD

**Issue by ethank** [tylerhall/sosumi#9]
I increased the timeout to 600 and I still get an error 'Unable to find location within '600' seconds' 

Is this still working given the latest mobileme features?

**Comment by tylerhall** [comment]
Yep, it still works - I just tested it. Make sure you're using the most recently updated version which uses Apple's "official" FMIP API. (Latest version was updated 2010-06-22.)

I'm not claiming it's impossible, but it's going to be very difficult for Sosumi to break in the near future.

**Comment by ethank** [comment]
Yeah, using it fresh from github.

I wonder if its because I have an iPad and a 4 in there, and a 3GS is stuck in there but not active. Might be freezing on that one.

**Comment by ethank** [comment]
Ahh, that was indeed it. I did a remote wipe and remove and it all works now. Awesome stuff. Thanks! Will be integrating this with my home automation system :)

**Comment by tylerhall** [comment]
Glad it's working.

I'm in the same boat. An iPad, iPhone 4, and a newly inactive 3GS. You can target the specific device you want location data from by passing a device number to the locate() function.

$device_num is just an integer 0 through n, representing the device you want. You can see a list of devices and their numbers by doing a print_r($sosumi->devices), or by just trying numbers until you find the one you want :)

Sidenote: it does take a little longer to find a device that hasn't been found recently. In my test a few minutes ago, it took about 30 seconds to do the first find. After that, it should be near instant for a while. But I've never seen it take longer than 30-60 seconds.
